Massive AI improvements, system prompts revised, motivation like health, motivation bar, AI now has memory and automatically summarizes its memory
GameDevWS2024/Game pull request #41
Opened 2024-12-04 19:27 UTC by Leo-Dev-2004

2024-12-04 19:27 UTC, Leo-Dev-2004 commented
The remaining problem is the damage and health of the player and combatally

2024-12-07 16:23 UTC, konradbausch requested changes
There need to be a few things changed, especially the code duplication

2024-12-07 16:23 UTC, konradbausch commented on scripts/Location.cs
This seems really unecesarry, like what is the difference to the Vector2d class provided my godot

2024-12-07 16:23 UTC, konradbausch commented on scripts/Enemy.cs
This is allready implemented in a reusable way if you use the Removable script and just connect it to the death signal of the healt, have a look at the ally script

2024-12-07 16:23 UTC, konradbausch commented on scripts/CombatAlly.cs
This seems like it copys the ally and parts of the enemy for the most part, just take the existing ally, move out the attack funcitonality from the enemy into a component and so you dont have the same code in two places

2024-12-07 16:23 UTC, konradbausch commented on scripts/Player.cs
also code duplication from the ally, which again suggests, that the functionality to take damage in the darkness, should be in a separate component that then can be added to the ally and the player.

2024-12-07 16:23 UTC, konradbausch commented on scripts/MotivationBar.cs
This also seems to be duplicated from the health bar, could also be made into a more modular component, but since it is that little code, it isnt as bad.

2024-12-07 16:23 UTC, konradbausch commented on scripts/Items/MapItem.cs
> +    public Location Location { get; set; }
Like here, just use a Vector 2d for the location

2024-12-07 18:41 UTC, konradbausch requested changes
Missed some things, since they weren't in the right folder

2024-12-07 18:41 UTC, konradbausch commented on scenes/levels/IntroText.cs
Missed this since it isnt in the right folder. Make sure, to configure everything that can be done over the editor like hardcoded position values or the content of the text field.

2024-12-07 18:41 UTC, konradbausch commented on example_prompt.txt
Move this into the right folder

2024-12-07 18:41 UTC, konradbausch commented on ally2_prompt.txt
also the wrong folder

2024-12-08 12:36 UTC, Leo-Dev-2004 commented
Oh damn I'm cooked

2025-01-18 17:03 UTC, closed without merging